# Generated by Django 3.1 on 2020-10-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poller_app', '0003_auto_20201023_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poller_app.question'),
            preserve_default=False,
        ),
    ]
